/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventory.gui;

import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.Timer;

/**
 *
 * @author Muhamad Ashraff
 */
public class frmDelete extends javax.swing.JFrame {

    int productId;
    double invValue;
    int proqty;
    boolean delStatus;
    Timer timer;
    int i = 0;
    frmdelLoad delLoad = new frmdelLoad();
    
    
    
    public frmDelete() {
        initComponents();

    }//DEFAULT CONSTRUCTOR

    public frmDelete(int productId) {
        this.productId = productId;
        initComponents();
        loadData(productId);
        playExclamation();
        btnConfirm.setEnabled(false);
    }//CONSTRUCTOR WITH PARAMTER
    
    public void loadData(int n){
      n=n-1;
      String strPath = "C:/Products.txt";
      String line;
      try (BufferedReader br = new BufferedReader(new FileReader(strPath))) {
          for (int i = 0; i < n; i++)
              br.readLine();
          line = br.readLine();
          System.out.println(line);
          String[] myData = line.split(",");
          System.out.println("Product ID     : " + myData[0]);
          System.out.println("Product Type   : " + myData[1]);
          System.out.println("Product Name   : " + myData[2]);
          System.out.println("Product Qty    : " + myData[3]);
          System.out.println("Product Price  : " + myData[4]);
          
          setTitle("Remove Product with ID : " + myData[0] + " ?");
          ctprodId.setText(myData[0]);
          ctprodType.setText(myData[1]);
          ctprodName.setText(myData[2]);
          ctprodQty.setText(myData[3]);
          ctprodPrice.setText(myData[4]);
          
          int Qty = Integer.parseInt(myData[3]);
          double price = Double.parseDouble(myData[4]);
          invValue = Qty*price;
          proqty = Qty;
          
      }
      catch(IOException e){
        System.out.println(e);
      }//END TRY CATCH
        
    }//END METHOD
    
    //METHOD TO GET IF DELETE IS DONE
    public boolean getdelStatus(){
        boolean delStat = delStatus;
        return delStat;
    }//END METHOD
    
    //METHOD TO CALCULATE CURRENT INVENTORT VALUE
    public double getcurrentinvValue(){
        double productInvval = invValue; 
        return productInvval;
    }//END METHOD
    
    //METHOD TO GET CURRENT INVENTORY QUANTITY
    public int getQuantity(){
        int getQty = proqty;
        return getQty;
    }//END METHOD
    
    //METHOD TO PLAY EXCLAMATION SOUNd
    private void playExclamation(){
        final Runnable runnable =
        (Runnable) Toolkit.getDefaultToolkit().getDesktopProperty("win.sound.asterisk");
        if (runnable != null) runnable.run();
    }//END METHOD

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblprodId2 = new javax.swing.JPanel();
        mainPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblprodType = new javax.swing.JLabel();
        lblprodName = new javax.swing.JLabel();
        lblprodQty = new javax.swing.JLabel();
        lblprodPrice = new javax.swing.JLabel();
        lblprodId = new javax.swing.JLabel();
        btnConfirm = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        ctprodId = new javax.swing.JLabel();
        ctprodType = new javax.swing.JLabel();
        ctprodName = new javax.swing.JLabel();
        ctprodQty = new javax.swing.JLabel();
        ctprodPrice = new javax.swing.JLabel();
        jcheckcnfrmDel = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Remove Product ?");
        setResizable(false);

        lblprodId2.setBackground(new java.awt.Color(255, 255, 255));

        mainPanel3.setBackground(new java.awt.Color(181, 79, 119));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete32.png"))); // NOI18N
        jLabel4.setText("Remove Product");

        javax.swing.GroupLayout mainPanel3Layout = new javax.swing.GroupLayout(mainPanel3);
        mainPanel3.setLayout(mainPanel3Layout);
        mainPanel3Layout.setHorizontalGroup(
            mainPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainPanel3Layout.setVerticalGroup(
            mainPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Delete this product ?");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Product Details");

        lblprodType.setText("Product Type :");

        lblprodName.setText("Product Name :");

        lblprodQty.setText("Product Qty :");

        lblprodPrice.setText("Product Price :");

        lblprodId.setText("Product ID :");

        btnConfirm.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        btnConfirm.setText("Confirm");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        ctprodId.setText("ctprodId");

        ctprodType.setText("ctprodType");

        ctprodName.setText("ctprodName");

        ctprodQty.setText("ctprodQty");

        ctprodPrice.setText("ctprodPrice");

        jcheckcnfrmDel.setBackground(new java.awt.Color(255, 255, 255));
        jcheckcnfrmDel.setText("Yes, I'm sure !");
        jcheckcnfrmDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcheckcnfrmDelActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel2.setText("<html>This action is irreversible. To prevent data loss<br>\nplease tick the checkbox below to confirm this action.</html>");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("WARNING !");

        javax.swing.GroupLayout lblprodId2Layout = new javax.swing.GroupLayout(lblprodId2);
        lblprodId2.setLayout(lblprodId2Layout);
        lblprodId2Layout.setHorizontalGroup(
            lblprodId2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(lblprodId2Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(lblprodId2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1)
                    .addGroup(lblprodId2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(lblprodId2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(lblprodId2Layout.createSequentialGroup()
                                .addGroup(lblprodId2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblprodId)
                                    .addComponent(lblprodType)
                                    .addComponent(lblprodName)
                                    .addComponent(lblprodQty)
                                    .addComponent(lblprodPrice))
                                .addGap(109, 109, 109)
                                .addGroup(lblprodId2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ctprodPrice)
                                    .addComponent(ctprodQty)
                                    .addComponent(ctprodName)
                                    .addComponent(ctprodType)
                                    .addComponent(ctprodId)))
                            .addGroup(lblprodId2Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(btnConfirm)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jcheckcnfrmDel))))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        lblprodId2Layout.setVerticalGroup(
            lblprodId2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblprodId2Layout.createSequentialGroup()
                .addComponent(mainPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(lblprodId2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(lblprodId2Layout.createSequentialGroup()
                        .addComponent(lblprodId)
                        .addGap(18, 18, 18)
                        .addComponent(lblprodType)
                        .addGap(18, 18, 18)
                        .addComponent(lblprodName)
                        .addGap(18, 18, 18)
                        .addComponent(lblprodQty)
                        .addGap(18, 18, 18)
                        .addComponent(lblprodPrice))
                    .addGroup(lblprodId2Layout.createSequentialGroup()
                        .addComponent(ctprodId)
                        .addGap(18, 18, 18)
                        .addComponent(ctprodType)
                        .addGap(18, 18, 18)
                        .addComponent(ctprodName)
                        .addGap(18, 18, 18)
                        .addComponent(ctprodQty)
                        .addGap(18, 18, 18)
                        .addComponent(ctprodPrice)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcheckcnfrmDel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(lblprodId2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirm)
                    .addComponent(btnCancel))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblprodId2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblprodId2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        
           timer = new Timer(100, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                  i++;
                    if(i==1){
                        dispose();//CLOSE FRAME
                        delLoad.setVisible(true);
                        delLoad.lbldelLoad.setText("Processing . . . ");
                    }//END IF
                    
                    if (i==15){
                    delLoad.lbldelLoad.setText("Deleting Product ID : "+ productId + " . . .");
                    }//END IF
                    
                    
                    if(i==50){
                       delLoad.dispose();  
                      //CREATE OBJECT DELETE PRODUCT AND PASS PRODUCT ID VALUE
                      deleteProduct dp = new deleteProduct(productId);
                      delStatus = true;
                      playExclamation();
                      new msgBox("Product with ID : "+productId+"\nhas been successfully deleted !","Product Deleted").showinfoMsg();  
                    }//END IF
                    
                    if(i>51){
                        timer.stop();
                        i=0;
                    }//END IF
            }//END PUBLIC VOID
        });
        timer.start();

        
    }//GEN-LAST:event_btnConfirmActionPerformed

    
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void jcheckcnfrmDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcheckcnfrmDelActionPerformed
        if (jcheckcnfrmDel.isSelected()){
            btnConfirm.setEnabled(true);
        } else {
            btnConfirm.setEnabled(false);
        }//END IF
    }//GEN-LAST:event_jcheckcnfrmDelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmDelete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JLabel ctprodId;
    private javax.swing.JLabel ctprodName;
    private javax.swing.JLabel ctprodPrice;
    private javax.swing.JLabel ctprodQty;
    private javax.swing.JLabel ctprodType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JCheckBox jcheckcnfrmDel;
    private javax.swing.JLabel lblprodId;
    private javax.swing.JPanel lblprodId2;
    private javax.swing.JLabel lblprodName;
    private javax.swing.JLabel lblprodPrice;
    private javax.swing.JLabel lblprodQty;
    private javax.swing.JLabel lblprodType;
    private javax.swing.JPanel mainPanel3;
    // End of variables declaration//GEN-END:variables
}
