package inventory.gui;

/**
 *
 * @author Muhamad Ashraff
 */

import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.*;  
import javax.swing.JOptionPane;
public class frmLogin extends javax.swing.JFrame {

    /**
     * Creates new form loginFrm
     */
    public frmLogin() {
        initComponents();
        jbLogin.setEnabled(false);
        lblstaffIdchecker.setText("");
    }//DEFAULT CONSTRUCTOR

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblstaffId = new javax.swing.JLabel();
        txtstaffId = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblstaffPass = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jbLogin = new javax.swing.JButton();
        jbClear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblstaffIdchecker = new javax.swing.JLabel();
        txtstaffPass = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jbClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(181, 79, 119));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(181, 79, 119));
        jLabel3.setText("Holla, please login to continue !");

        lblstaffId.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lblstaffId.setText("Staff ID :");

        txtstaffId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtstaffId.setText("Staff ID");
        txtstaffId.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtstaffId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtstaffIdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtstaffIdFocusLost(evt);
            }
        });
        txtstaffId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtstaffIdKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtstaffIdKeyReleased(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(181, 79, 119));

        lblstaffPass.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lblstaffPass.setText("Password :");

        jSeparator2.setForeground(new java.awt.Color(181, 79, 119));

        jbLogin.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jbLogin.setForeground(new java.awt.Color(0, 153, 0));
        jbLogin.setText("Login");
        jbLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLoginActionPerformed(evt);
            }
        });
        jbLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbLoginKeyPressed(evt);
            }
        });

        jbClear.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jbClear.setText("Clear");

        lblstaffIdchecker.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblstaffIdchecker.setForeground(new java.awt.Color(255, 0, 102));
        lblstaffIdchecker.setText("notifystaffIdnotint");

        txtstaffPass.setText("Password");
        txtstaffPass.setBorder(null);
        txtstaffPass.setPreferredSize(new java.awt.Dimension(61, 22));
        txtstaffPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtstaffPassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtstaffPassFocusLost(evt);
            }
        });
        txtstaffPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtstaffPassKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jbClear, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jbLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblstaffPass)
                                .addComponent(lblstaffId))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblstaffIdchecker)
                                .addComponent(txtstaffId, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                                .addComponent(jSeparator1)
                                .addComponent(jSeparator2)
                                .addComponent(txtstaffPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblstaffId)
                    .addComponent(txtstaffId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblstaffPass)
                    .addComponent(txtstaffPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblstaffIdchecker)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbClear, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        jLabel7.setBackground(new java.awt.Color(204, 204, 204));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 204, 153));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("<html><center> Inventory Management System \n<br>v1.0.0.0</center> </html>");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory.png"))); // NOI18N

        jbClose.setBackground(new java.awt.Color(255, 153, 153));
        jbClose.setText("Close");
        jbClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbClose, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap(231, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addGap(60, 60, 60)))
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 60, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbClose)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLoginActionPerformed
        //WHEN LOGIN BUTTON IS CLICKED. CALL METHOD LOGIN()
        Login();
        
    }//GEN-LAST:event_jbLoginActionPerformed
    
    //METHOD TO SUBMIT VALUE OF JTEXTFIELD AND JPASSWORD TO LOGIN
    public void Login(){
        //USING TRY CATCH
        try {
            //ASSIGN VALUE OF TEXTFIELD INTO THE VARIABLE
            int staffId = Integer.parseInt(txtstaffId.getText());
            String staffPass = String.valueOf(txtstaffPass.getPassword());

            //CREATE OBJECT LOGIN
            checkLogin login = new checkLogin(staffId, staffPass);

            //GET STAFF NAME FROM OBJECT.METHOD 
            String staffName = login.getstaffName();

            //GET STAFF ROLE FROM OBJECT.METHOD 
            String staffRole = login.getstaffRole();

            //GET BOOLEAN VALUE FROM OBJECT.METHOD VERIFYLOGIN
            boolean isValid = login.verifyLogin();

            //USING IF STRUCTURE TO DETERMINE IF THE LOGIN INFORMATION IS VALID
            if (isValid == true){
            playExclamation();

            //SHOW SUCCESS LOGIN MSGBOX
            String message = "Staff ID : " + staffId + "\nStaff Name : "+staffName+"\nhas successfully logged in!";
            new msgBox(message,"Logged In").showinfoMsg();

            //CREATE MAINMENU FRAME
            frmMainmenu mainmenu = new frmMainmenu();

            //INVOKE METHOD LOGGEDINAS() AND PASS PARAMETER OF STAFF NAME AND ID
            mainmenu.loggedinAs(staffName, staffId, staffRole);
            mainmenu.setVisible(true);
            dispose();
            }
            else {

            //IF STAFF ID AND PASSWORD IS NOT VALID. THEN SHOW ERROR MSGBOX
            playExclamation();
            new msgBox("Username or password is invalid.\nPlease try again !","Invalid Login").showerrorMsg();
            }//END IF
        } catch (NullPointerException e) {
            playExclamation();
            new msgBox("Username or password is invalid.\nPlease try again !","Invalid Login").showerrorMsg();
        }//END TRY CATCH
        
    }//END METHOD
    
    //KEYEVENT IF STAFF ID IS NOT INTEGER
        //SHOW MSG LABEL THAT STAFF ID MUST BE A NUMBER ONLY
    private void txtstaffIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtstaffIdKeyReleased
        //USING TRY CATCH
        try {
        Integer.parseInt(txtstaffId.getText());
        lblstaffIdchecker.setText("");
        jbLogin.setEnabled(true);
        }//CATCH AN ERROR IF USER INPUT THE VALUE OF STAFF ID IS NOT A NUMBER
        catch (NumberFormatException e) {
            lblstaffIdchecker.setText("Staff ID must be numeric value only");
            jbLogin.setEnabled(false);
        }//END TRY CATCH
    }//GEN-LAST:event_txtstaffIdKeyReleased

    //IF FOCUS GAINED AT THE JTEXTFIELD
      //REMOVE PLACEHOLDER TEXT
    private void txtstaffIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtstaffIdFocusGained
        if (txtstaffId.getText().equals("Staff ID")){
            txtstaffId.setText("");
        }//END IF
    }//GEN-LAST:event_txtstaffIdFocusGained
    
    //IF FOCUS LOST AT THE JTEXTFIELD
      //REMOVE PLACEHOLDER TEXT
    private void txtstaffIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtstaffIdFocusLost
            if (txtstaffId.getText().equals("")){
            txtstaffId.setText("Staff ID");
        }//END IF
    }//GEN-LAST:event_txtstaffIdFocusLost

    //IF FOCUS GAINED AT THE JTEXTFIELD
        //REMOVE PLACEHOLDER TEXT
    private void txtstaffPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtstaffPassFocusGained
       if (String.valueOf(txtstaffPass.getPassword()).equals("Password")){
       txtstaffPass.setText("");
       }//END IF
    }//GEN-LAST:event_txtstaffPassFocusGained

    //IF FOCUS GAINED AT THE JTEXTFIELD
      //REMOVE PLACEHOLDER TEXT
    private void txtstaffPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtstaffPassFocusLost
       if (String.valueOf(txtstaffPass.getPassword()).equals("")){
       txtstaffPass.setText("Password");
       }
    }//GEN-LAST:event_txtstaffPassFocusLost

    //IF AN ENTER KEY IS PRESSED
    private void jbLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbLoginKeyPressed
        //USING IF STRUCTURE TO DETERMINE IF USING INPUT ENTER KEY
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Login();
        }//END IF
    }//GEN-LAST:event_jbLoginKeyPressed
    
    //IF AN ENTER KEY IS PRESSED
    private void txtstaffPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtstaffPassKeyPressed
        //USING IF STRUCTURE TO DETERMINE IF USING INPUT ENTER KEY
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Login();
        }//END IF
    }//GEN-LAST:event_txtstaffPassKeyPressed
    
    //IF AN ENTER KEY IS PRESSED
    private void txtstaffIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtstaffIdKeyPressed
        //USING IF STRUCTURE TO DETERMINE IF USING INPUT ENTER KEY
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Login();
        }//END IF
    }//GEN-LAST:event_txtstaffIdKeyPressed
    
    //IF CLOSE BUTTON IS PRESSED
    private void jbCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCloseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jbCloseActionPerformed

   //METHOD TO PLAY EXCLAMATION SOUND FOR MSGBOX
    private void playExclamation(){
        final Runnable runnable =
        (Runnable) Toolkit.getDefaultToolkit().getDesktopProperty("win.sound.asterisk");
        if (runnable != null) runnable.run();
    }//END METHOD
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLogin().setVisible(true);
            }
        });
    }//END MAIN

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton jbClear;
    private javax.swing.JButton jbClose;
    private javax.swing.JButton jbLogin;
    private javax.swing.JLabel lblstaffId;
    private javax.swing.JLabel lblstaffIdchecker;
    private javax.swing.JLabel lblstaffPass;
    private javax.swing.JTextField txtstaffId;
    private javax.swing.JPasswordField txtstaffPass;
    // End of variables declaration//GEN-END:variables
}



