/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventory.gui;


import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.FileWriter;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.HashSet;
import javax.accessibility.AccessibleRole;
import javax.swing.ButtonGroup;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Muhamad Ashraff
 */
public class frmMainmenu extends javax.swing.JFrame {
    
    int mystaffId;
    boolean delStatus;
    
    Timer timer;
    int i = 0;
    int j = 0;
    frmsrchLoad loading = new frmsrchLoad();
    frmDelete delete;
    /**
     * Creates new form mainmenuFrm
     */
    public frmMainmenu() {
        initComponents();
        loadData();
        setExtendedState(MAXIMIZED_BOTH);
        lblindInvVal.setText(" ");
        lblminusinvVal.setText(" ");
        lblminusProd.setText(" ");
        lblminusQty.setText(" ");
        
        //GROUP RADIO BUTTON
        ButtonGroup btnGroup = new ButtonGroup();
        btnGroup.add(jrbDefault);
        btnGroup.add(jrbOceanFive);
        btnGroup.add(jrbCheerUp);
        
    }//DEFAULT CONSTRUCTOR

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        mainPanel = new javax.swing.JPanel();
        subPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jptotQty = new javax.swing.JPanel();
        txtlbltotQty = new javax.swing.JLabel();
        lbltotQty = new javax.swing.JLabel();
        lblminusQty = new javax.swing.JLabel();
        txtsearchBox = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btnSearch = new javax.swing.JButton();
        jptotProd = new javax.swing.JPanel();
        txtlbltotProd = new javax.swing.JLabel();
        lblitemNo = new javax.swing.JLabel();
        lblminusProd = new javax.swing.JLabel();
        jpinvVal = new javax.swing.JPanel();
        txtlblinvval = new javax.swing.JLabel();
        lblinventoryVal = new javax.swing.JLabel();
        lblminusinvVal = new javax.swing.JLabel();
        lblindInvVal = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblsessionName = new javax.swing.JLabel();
        lblsessionName1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiAdd = new javax.swing.JMenuItem();
        jmiEdit = new javax.swing.JMenuItem();
        jmiDelete = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jmiExport = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jmiLogout = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmiprodinvVal = new javax.swing.JCheckBoxMenuItem();
        jmitotinvVal = new javax.swing.JCheckBoxMenuItem();
        jmitotprodCnt = new javax.swing.JCheckBoxMenuItem();
        jmitotprodQty = new javax.swing.JCheckBoxMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jmiSearch = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jmiMngAcc = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jmiStaffAcc = new javax.swing.JMenuItem();
        jmicrtAcc = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jrbDefault = new javax.swing.JRadioButtonMenuItem();
        jrbOceanFive = new javax.swing.JRadioButtonMenuItem();
        jrbCheerUp = new javax.swing.JRadioButtonMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmikbshrtct = new javax.swing.JMenuItem();
        jmiAbout = new javax.swing.JMenuItem();

        jScrollPane2.setViewportView(jTree1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Inventory Management System");
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        mainPanel.setBackground(new java.awt.Color(181, 79, 119));

        subPanel.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product Type", "Product Name", "Quantity", "Price", "Brand", "Model"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable1MouseReleased(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        btnAdd.setText("Add  (Ctrl+A)");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit.png"))); // NOI18N
        btnEdit.setText("Edit  (Ctrl+E)");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(255, 204, 204));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        btnDelete.setText("Delete  (Ctrl+D)");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jptotQty.setBackground(new java.awt.Color(48, 213, 200));

        txtlbltotQty.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtlbltotQty.setForeground(new java.awt.Color(204, 255, 255));
        txtlbltotQty.setText("Total Quantity :");

        lbltotQty.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        lbltotQty.setForeground(new java.awt.Color(255, 255, 255));
        lbltotQty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltotQty.setText("totQty");

        lblminusQty.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblminusQty.setForeground(new java.awt.Color(204, 255, 204));
        lblminusQty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblminusQty.setText("- 0 Quantity");

        javax.swing.GroupLayout jptotQtyLayout = new javax.swing.GroupLayout(jptotQty);
        jptotQty.setLayout(jptotQtyLayout);
        jptotQtyLayout.setHorizontalGroup(
            jptotQtyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jptotQtyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jptotQtyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jptotQtyLayout.createSequentialGroup()
                        .addComponent(txtlbltotQty)
                        .addGap(0, 63, Short.MAX_VALUE))
                    .addComponent(lbltotQty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblminusQty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jptotQtyLayout.setVerticalGroup(
            jptotQtyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jptotQtyLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtlbltotQty)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbltotQty)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblminusQty, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        txtsearchBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtsearchBox.setText("Search here...");
        txtsearchBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtsearchBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtsearchBoxFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtsearchBoxFocusLost(evt);
            }
        });
        txtsearchBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtsearchBoxKeyPressed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(181, 79, 119));

        btnSearch.setBackground(new java.awt.Color(153, 255, 153));
        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        btnSearch.setText("Search...  (F3)");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jptotProd.setBackground(new java.awt.Color(48, 213, 200));

        txtlbltotProd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtlbltotProd.setForeground(new java.awt.Color(204, 255, 255));
        txtlbltotProd.setText("Total Products :");

        lblitemNo.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        lblitemNo.setForeground(new java.awt.Color(255, 255, 255));
        lblitemNo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblitemNo.setText("itemNo");

        lblminusProd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblminusProd.setForeground(new java.awt.Color(204, 255, 204));
        lblminusProd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblminusProd.setText("- 0 Product");

        javax.swing.GroupLayout jptotProdLayout = new javax.swing.GroupLayout(jptotProd);
        jptotProd.setLayout(jptotProdLayout);
        jptotProdLayout.setHorizontalGroup(
            jptotProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jptotProdLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jptotProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblitemNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jptotProdLayout.createSequentialGroup()
                        .addComponent(txtlbltotProd)
                        .addGap(0, 63, Short.MAX_VALUE))
                    .addComponent(lblminusProd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jptotProdLayout.setVerticalGroup(
            jptotProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jptotProdLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtlbltotProd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblitemNo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblminusProd, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpinvVal.setBackground(new java.awt.Color(48, 213, 200));

        txtlblinvval.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtlblinvval.setForeground(new java.awt.Color(204, 255, 255));
        txtlblinvval.setText("Inventory Value :");

        lblinventoryVal.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        lblinventoryVal.setForeground(new java.awt.Color(255, 255, 255));
        lblinventoryVal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblinventoryVal.setText("invVal");

        lblminusinvVal.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblminusinvVal.setForeground(new java.awt.Color(204, 255, 204));
        lblminusinvVal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblminusinvVal.setText("- RM0");

        javax.swing.GroupLayout jpinvValLayout = new javax.swing.GroupLayout(jpinvVal);
        jpinvVal.setLayout(jpinvValLayout);
        jpinvValLayout.setHorizontalGroup(
            jpinvValLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpinvValLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpinvValLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblminusinvVal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpinvValLayout.createSequentialGroup()
                        .addComponent(txtlblinvval)
                        .addGap(0, 54, Short.MAX_VALUE))
                    .addComponent(lblinventoryVal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpinvValLayout.setVerticalGroup(
            jpinvValLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpinvValLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtlblinvval)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblinventoryVal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblminusinvVal)
                .addGap(5, 5, 5))
        );

        lblindInvVal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblindInvVal.setForeground(new java.awt.Color(0, 153, 153));
        lblindInvVal.setText("Product ID [ID] has inventory value of RM [inventoryValue]");

        javax.swing.GroupLayout subPanelLayout = new javax.swing.GroupLayout(subPanel);
        subPanel.setLayout(subPanelLayout);
        subPanelLayout.setHorizontalGroup(
            subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subPanelLayout.createSequentialGroup()
                        .addComponent(lblindInvVal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 282, Short.MAX_VALUE)
                        .addComponent(jpinvVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jptotProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jptotQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(subPanelLayout.createSequentialGroup()
                        .addGroup(subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(subPanelLayout.createSequentialGroup()
                                .addComponent(txtsearchBox)
                                .addGap(38, 38, 38)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(subPanelLayout.createSequentialGroup()
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        subPanelLayout.setVerticalGroup(
            subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnEdit)
                    .addComponent(btnDelete))
                .addGap(18, 18, 18)
                .addGroup(subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(subPanelLayout.createSequentialGroup()
                        .addComponent(txtsearchBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblindInvVal)
                    .addGroup(subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jptotProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jpinvVal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jptotQty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storename_default.gif"))); // NOI18N
        jLabel2.setToolTipText("");

        lblsessionName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblsessionName.setForeground(new java.awt.Color(255, 255, 255));
        lblsessionName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblsessionName.setText("Logged in as : ");

        lblsessionName1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 11)); // NOI18N
        lblsessionName1.setForeground(new java.awt.Color(255, 204, 255));
        lblsessionName1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblsessionName1.setText("<html> <p style=\"text-align:right;\"> <u>Ashraff</u> | <u>Hadif</u> | <u>Nabilah</u> | <u>Fatihah</u>  <br> © 2021 Ashfabidif   </p> </html>");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblsessionName, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(subPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblsessionName1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(lblsessionName)
                .addGap(4, 4, 4)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(subPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblsessionName1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(188, 188, 188))
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));

        jMenu1.setText("File");

        jmiAdd.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmiAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        jmiAdd.setText("Add Products");
        jmiAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAddActionPerformed(evt);
            }
        });
        jMenu1.add(jmiAdd);

        jmiEdit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmiEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit.png"))); // NOI18N
        jmiEdit.setText("Edit Products");
        jmiEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEditActionPerformed(evt);
            }
        });
        jMenu1.add(jmiEdit);

        jmiDelete.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmiDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        jmiDelete.setText("Delete Products");
        jmiDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiDeleteActionPerformed(evt);
            }
        });
        jMenu1.add(jmiDelete);
        jMenu1.add(jSeparator2);

        jmiExport.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmiExport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/export.png"))); // NOI18N
        jmiExport.setText("Export to Text File");
        jmiExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiExportActionPerformed(evt);
            }
        });
        jMenu1.add(jmiExport);
        jMenu1.add(jSeparator3);

        jmiLogout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jmiLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logout.png"))); // NOI18N
        jmiLogout.setText("Logout");
        jmiLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiLogoutActionPerformed(evt);
            }
        });
        jMenu1.add(jmiLogout);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("View");

        jmiprodinvVal.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jmiprodinvVal.setSelected(true);
        jmiprodinvVal.setText("Product Inventory Value");
        jmiprodinvVal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/invVal.png"))); // NOI18N
        jmiprodinvVal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiprodinvValActionPerformed(evt);
            }
        });
        jMenu2.add(jmiprodinvVal);

        jmitotinvVal.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jmitotinvVal.setSelected(true);
        jmitotinvVal.setText("Total Inventory Value");
        jmitotinvVal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/totinvVal.png"))); // NOI18N
        jmitotinvVal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmitotinvValActionPerformed(evt);
            }
        });
        jMenu2.add(jmitotinvVal);

        jmitotprodCnt.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jmitotprodCnt.setSelected(true);
        jmitotprodCnt.setText("Total Products Count");
        jmitotprodCnt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prodCount.png"))); // NOI18N
        jmitotprodCnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmitotprodCntActionPerformed(evt);
            }
        });
        jMenu2.add(jmitotprodCnt);

        jmitotprodQty.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jmitotprodQty.setSelected(true);
        jmitotprodQty.setText("Total Products Quantity");
        jmitotprodQty.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prodQty.png"))); // NOI18N
        jmitotprodQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmitotprodQtyActionPerformed(evt);
            }
        });
        jMenu2.add(jmitotprodQty);

        jMenuBar1.add(jMenu2);

        jMenu6.setText("Navigate");

        jmiSearch.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        jmiSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        jmiSearch.setText("Search Products");
        jmiSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSearchActionPerformed(evt);
            }
        });
        jMenu6.add(jmiSearch);

        jMenuBar1.add(jMenu6);

        jMenu4.setText("Account");

        jmiMngAcc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmiMngAcc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mngAcc.png"))); // NOI18N
        jmiMngAcc.setText("Manage My Account");
        jmiMngAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiMngAccActionPerformed(evt);
            }
        });
        jMenu4.add(jmiMngAcc);
        jMenu4.add(jSeparator4);

        jmiStaffAcc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmiStaffAcc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staffAccList.png"))); // NOI18N
        jmiStaffAcc.setText("View Staff Account List");
        jmiStaffAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiStaffAccActionPerformed(evt);
            }
        });
        jMenu4.add(jmiStaffAcc);

        jmicrtAcc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmicrtAcc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staffNewAcc.png"))); // NOI18N
        jmicrtAcc.setText("Create New Account");
        jmicrtAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmicrtAccActionPerformed(evt);
            }
        });
        jMenu4.add(jmicrtAcc);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Theme");

        jrbDefault.setSelected(true);
        jrbDefault.setText("Default");
        jrbDefault.setIcon(new javax.swing.ImageIcon(getClass().getResource("/theme_default.png"))); // NOI18N
        jrbDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbDefaultActionPerformed(evt);
            }
        });
        jMenu5.add(jrbDefault);

        jrbOceanFive.setSelected(true);
        jrbOceanFive.setText("Ocean Five");
        jrbOceanFive.setIcon(new javax.swing.ImageIcon(getClass().getResource("/theme_oceanfive.png"))); // NOI18N
        jrbOceanFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbOceanFiveActionPerformed(evt);
            }
        });
        jMenu5.add(jrbOceanFive);

        jrbCheerUp.setSelected(true);
        jrbCheerUp.setText("Cheer Up");
        jrbCheerUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/theme_cheerup.png"))); // NOI18N
        jrbCheerUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbCheerUpActionPerformed(evt);
            }
        });
        jMenu5.add(jrbCheerUp);

        jMenuBar1.add(jMenu5);

        jMenu3.setText("Help");

        jmikbshrtct.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jmikbshrtct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/keyboard.png"))); // NOI18N
        jmikbshrtct.setText("Keyboard Shortcuts");
        jmikbshrtct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmikbshrtctActionPerformed(evt);
            }
        });
        jMenu3.add(jmikbshrtct);

        jmiAbout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        jmiAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/about.png"))); // NOI18N
        jmiAbout.setText("About");
        jmiAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAboutActionPerformed(evt);
            }
        });
        jMenu3.add(jmiAbout);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        //CALL METHOD OF ADDPRODUCT()
        addProduct();
    }//GEN-LAST:event_btnAddActionPerformed
    
    //METHOD TO OPEN A NEW FRAME TO ADD PRODUCT
    private void addProduct(){
        frmAdd addFrame = new frmAdd();
        addFrame.setVisible(true);
    }//END METHOD
    

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        //CALL METHOD OF EDITPRODUCT()
        editProduct();
    }//GEN-LAST:event_btnEditActionPerformed
    
    //METHOD TO EDIT PRODUCT FROM THE VALUE OF JTABLE
    private void editProduct(){
        
        //USING TRY CATCH
          //TO GET SELECTED ROW NO OF JTABLE FOR FETCHING PRODUCT ID
        try {
             //DECLARE VARIABLE
                //ASSIGNED VALUE OF ROW,INDEX AND PRODUCT ID FROM JTABLE
             int selectedRowIndex = jTable1.getSelectedRow();
             int getselectedId = Integer.parseInt(jTable1.getModel().getValueAt(selectedRowIndex, 0).toString()); //TO GET ROW NUMBER
             
             //CREATE NEW FRAME EDIT
             frmEdit prodEdit = new frmEdit();
             
             //INVOKE METHOD LOAD DATA WITH PARAMETER OF SELECTED PRODUCT ID
             prodEdit.loadData(getselectedId);
             
             //SHOW EDIT FRAME
             prodEdit.setVisible(true);
        }
        //CATCH ARRAY INDEX OUT OF BOUND IF NONE OF THE JTABLE ROW IS SELECTED
        catch (ArrayIndexOutOfBoundsException e) {
            //CREATE OBJECT AND INVOKE METHOD TO SHOW WARNING MESSAGE BOX
            playExclamation();
            new msgBox("No Product Selected.\nSelect at least one product to continue.","WARNING").showwarningMsg();
        }//END TRY CATCH

    }//END METHOD


    //METHOD TO SHOW LOGGED IN AS
    public void loggedinAs(String staffName, int staffId, String staffRole){
        
        lblsessionName.setText("Logged in as : " + staffName + " |  Staff ID : " + staffId + "  ");
        setTitle("Inventory Management System ["+staffRole+"]");
        mystaffId = staffId;
        
    }//END METHOD
    
    
    
    //USING EVENT FORM WINDOWS ACTIVED TO GET AUTOMATED RELOAD OF JTABLE
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        reloadTable(); //CALL METHOD RELOADTABLE() IF FRAME IS ACTIVATED
    }//GEN-LAST:event_formWindowActivated
   
    //IF FOCUS LOST AT THE JTEXTFIELD
      //REMOVE PLACEHOLDER TEXT
    private void txtsearchBoxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtsearchBoxFocusLost
        if (txtsearchBox.getText().equals("")){
            txtsearchBox.setText("Search here...");
        }//END IF
    }//GEN-LAST:event_txtsearchBoxFocusLost

    //IF FOCUS LOST AT THE JTEXTFIELD
      //REMOVE PLACEHOLDER TEXT
    private void txtsearchBoxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtsearchBoxFocusGained
        if (txtsearchBox.getText().equals("Search here...")){
            txtsearchBox.setText("");
        }//END IF
    }//GEN-LAST:event_txtsearchBoxFocusGained

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        //CALL OUT METHOD DELETEPRODUCTS()
        deleteProducts();
        //CALL OUT METHOD DLTFRMSTATUS TO DETERMINE IF FRAME DELETE IS ACTIVE OR DISPOSED
         //THIS METHOD TO BE USED FOR GET IF A PRODUCT HAS BEEN DELETED
        dltfrmStatus();
    }//GEN-LAST:event_btnDeleteActionPerformed
    
    //METHOD TO DELETE PRODUCTS
    private void deleteProducts(){
          //USING TRY CATCH
          //TO GET SELECTED ROW NO OF JTABLE FOR FETCHING PRODUCT ID
        try {
             //DECLARE VARIABLE
                //ASSIGNED VALUE OF ROW,INDEX AND PRODUCT ID FROM JTABLE            
             int selectedRowIndex = jTable1.getSelectedRow(); //GET SELECTED ROW INDEX
             int getselectedId = Integer.parseInt(jTable1.getModel().getValueAt(selectedRowIndex, 0).toString()); 
             //TO GET PRODUCT ID VALUE
             
             //SHOW DELETE FRAME
             delete = new frmDelete(getselectedId);
             delete.setVisible(true);
             delete.setAlwaysOnTop(true);
        }
        //CATCH ARRAY INDEX OUT OF BOUND IF NONE OF THE JTABLE ROW IS SELECTED
        catch (ArrayIndexOutOfBoundsException e) {
            //CREATE OBJECT AND INVOKE METHOD TO SHOW WARNING MESSAGE BOX
            playExclamation();
            new msgBox("No Product Selected.\nSelect at least one product to continue.","WARNING").showwarningMsg();
        }//END TRY CATCH
        
    }//END METHOD
    
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        //CALL OUT METHOD ENTHERSEARCH()
        enterSearch();
    }//GEN-LAST:event_btnSearchActionPerformed
    
    //IF ENTER KEY IS PRESSED ON SEARCH TEXTFIELD
    private void txtsearchBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchBoxKeyPressed
        //USING IF STRUCTURE TO DETERMINE IF USING INPUT ENTER KEY
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            enterSearch();
        }//END IF
    }//GEN-LAST:event_txtsearchBoxKeyPressed

    private void jTable1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseReleased
        //CALL METHOD TO SHOW STATUS OF PRICE OF PRODUCT INVENTORY VALUE
        eachinventoryValue();
    }//GEN-LAST:event_jTable1MouseReleased

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        //CALL METHOD TO SHOW STATUS OF PRICE OF PRODUCT INVENTORY VALUE
        eachinventoryValue();
    }//GEN-LAST:event_jTable1KeyReleased

    private void jmiAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAboutActionPerformed
        //CREATE NEW FRAME ABOUT AND SHOW FRAME
        frmAbout about = new frmAbout();
        about.setVisible(true);
    }//GEN-LAST:event_jmiAboutActionPerformed

    private void jmiAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAddActionPerformed
        //CALL OUT METHOD ADDPRODUCT()
        addProduct();
    }//GEN-LAST:event_jmiAddActionPerformed

    private void jmiDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiDeleteActionPerformed
        //CALL OUT METHOD DELETEPRODUCT()
        deleteProducts();
    }//GEN-LAST:event_jmiDeleteActionPerformed

    private void jmiEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiEditActionPerformed
        //CALL OUT METHOD EDITPRODUCT()
        editProduct();
    }//GEN-LAST:event_jmiEditActionPerformed

    private void jmiLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiLogoutActionPerformed
       dispose();
    }//GEN-LAST:event_jmiLogoutActionPerformed

    private void jmiprodinvValActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiprodinvValActionPerformed
        //CHECKBOX TO SHOW OR HIDE INDIVIDUAL INVENTORY VALUE LABEL
        if (jmiprodinvVal.isSelected()){
            lblindInvVal.setVisible(true);
        }else {
            lblindInvVal.setVisible(false);
        }//END IF
        
    }//GEN-LAST:event_jmiprodinvValActionPerformed

    private void jmitotinvValActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmitotinvValActionPerformed
        //CHECKBOX TO SHOW OR HIDE JPANEL OF TOTAL INVENTORY VALUE   
        if (jmitotinvVal.isSelected()){
            jpinvVal.setVisible(true);
        }else {
            jpinvVal.setVisible(false);
        }//END IF
        
    }//GEN-LAST:event_jmitotinvValActionPerformed

    private void jmitotprodCntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmitotprodCntActionPerformed
        //CHECKBOX TO SHOW OR HIDE JPANEL OF TOTAL PRODUCT NUMBER
        if (jmitotprodCnt.isSelected()){
            jptotProd.setVisible(true);
        }else {
            jptotProd.setVisible(false);
        }//END IF
        
    }//GEN-LAST:event_jmitotprodCntActionPerformed

    private void jmitotprodQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmitotprodQtyActionPerformed
        //CHECKBOX TO SHOW OR HIDE JPANEL OF TOTAL PRODUCT QUANTITY
        if (jmitotprodQty.isSelected()) {
            jptotQty.setVisible(true);
        }else {
            jptotQty.setVisible(false);
        }//END IF
        
    }//GEN-LAST:event_jmitotprodQtyActionPerformed

    private void jmiSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSearchActionPerformed
        //CREATE AND SHOW MINISEARCH FRAME
        frmminiSearch miniSearch = new frmminiSearch();
        miniSearch.setVisible(true);
    
    }//GEN-LAST:event_jmiSearchActionPerformed

    private void jmiStaffAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiStaffAccActionPerformed
        //CREATE AND SHOW FRAME VIEWSTAFF ACCOUNT
        frmviewUser viewStaff = new frmviewUser();
        viewStaff.setVisible(true);
        
        //INVOKE METHOD VALIDATEUSER() WITH PARAMETER VALUE OF STAFFID
         //TO DETERMINE IF USER IS ADMINISTRATOR OR A STAFF
        viewStaff.validateUser(mystaffId);
    }//GEN-LAST:event_jmiStaffAccActionPerformed

    private void jmicrtAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmicrtAccActionPerformed
        //CREATE AND SHOW FRAME ADDUSER
        frmaddUser addUser = new frmaddUser();
        addUser.setVisible(true);

        //INVOKE METHOD VALIDATEUSER() WITH PARAMETER VALUE OF STAFFID
         //TO DETERMINE IF USER IS AN ADMINISTRATOR OR A STAFF        
        addUser.validateUser(mystaffId);
    }//GEN-LAST:event_jmicrtAccActionPerformed

    private void jmiExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiExportActionPerformed
        //CALL METHOD EXPORTTOFILE()
        exporttoFile();
    }//GEN-LAST:event_jmiExportActionPerformed

    private void jmiMngAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiMngAccActionPerformed
        //CREATE AND SHOW FRAME MANAGE ACCOUNT
         //INVOKE WITH THE VALUE OF STAFF ID AS THE PARAMETER
         //VALUE OF STAFF ID IS TO DETERMINE IF USER IS AN ADMINISTRATOR OR A STAFF
        frmMngAcc mngAcc = new frmMngAcc(mystaffId);
        mngAcc.setVisible(true);
    }//GEN-LAST:event_jmiMngAccActionPerformed

    private void jmikbshrtctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmikbshrtctActionPerformed
        //CREATE AND SHOW FRAME KEYBOARD SHORTCUT GUIDELINES
        frmkbShrct keyboardShrct = new frmkbShrct();
        keyboardShrct.setVisible(true);
    }//GEN-LAST:event_jmikbshrtctActionPerformed

        //BY USING EVENT WINDOW CLOSED
         //TO GO BACK TO LOGIN FORM
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
            frmLogin login = new frmLogin();
            frmLoading loadOut = new frmLoading();

            timer = new Timer(100, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                  j++;
                    if(j==1){
                        loadOut.setVisible(true);
                        loadOut.lblLoad.setText("Logging out . . .");
                        
                    }//END IF
                    
                    if(j==25){
                        loadOut.dispose();
                        
                        login.setVisible(true);
                        
                    }//END IF
                    
                    if(j>26){
                        dispose();
                        timer.stop();
                        j=0;
                    }//END IF
            }//END PUBLIC VOID
        });
        timer.start();
    }//GEN-LAST:event_formWindowClosed
        
    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
        //CALL METHOD DLTFRMSTATUS()
        dltfrmStatus();
    }//GEN-LAST:event_formWindowLostFocus

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        //CALL METHOD DLTFRMSTATUS()
        dltfrmStatus();
    }//GEN-LAST:event_formWindowGainedFocus

    //THIS IS RADIO BUTTON ACTION FOR THEME SELECTION
    private void jrbOceanFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbOceanFiveActionPerformed
        subPanel.setBackground(new Color(231, 239, 233));
        txtsearchBox.setBackground(new Color(231, 239, 233));
        mainPanel.setBackground(new Color(79, 164, 220)); //
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storename_oceanfive.gif")));
        jpinvVal.setBackground(new Color(20, 188, 199)); //new Color(20, 188, 199)
        jptotProd.setBackground(new Color(20, 188, 199));
        jptotQty.setBackground(new Color(20, 188, 199));
        txtlblinvval.setForeground(new Color(204,255,255));
        txtlbltotProd.setForeground(new Color(204,255,255));
        txtlbltotQty.setForeground(new Color(204,255,255));
        lblsessionName.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_jrbOceanFiveActionPerformed

    private void jrbCheerUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbCheerUpActionPerformed
        subPanel.setBackground(new Color(239, 239, 239));
        txtsearchBox.setBackground(new Color(239, 239, 239));
        mainPanel.setBackground(new Color(244, 197, 61));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storename_cheerup.gif")));        
        jpinvVal.setBackground(new Color(242, 170, 175));
        jptotProd.setBackground(new Color(242, 170, 175));
        jptotQty.setBackground(new Color(242, 170, 175));
        txtlblinvval.setForeground(new Color(157, 85, 90));
        txtlbltotProd.setForeground(new Color(157, 85, 90));
        txtlbltotQty.setForeground(new Color(157, 85, 90));
        lblsessionName.setForeground(new Color(51, 51, 49));
    }//GEN-LAST:event_jrbCheerUpActionPerformed

    private void jrbDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbDefaultActionPerformed
        subPanel.setBackground(new Color(255,255,255));
        txtsearchBox.setBackground(new Color(255,255,255));
        mainPanel.setBackground(new Color(181,79,119));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storename_default.gif"))); 
        jpinvVal.setBackground(new Color(48,213,200));
        jptotProd.setBackground(new Color(48,213,200));
        jptotQty.setBackground(new Color(48,213,200));
        txtlblinvval.setForeground(new Color(204,255,255));
        txtlbltotProd.setForeground(new Color(204,255,255));
        txtlbltotQty.setForeground(new Color(204,255,255));
        lblsessionName.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_jrbDefaultActionPerformed
    
    //METHOD TO GET IF PRODUCT IS DELETED TO SHOW DEDUCTED VALUE OF INVENTORY
    public void dltfrmStatus(){
        
        //USING TRY CATCH
        try {
            
            //VARIABLE DECLARATION
            String dltfrmStatus = delete.isDisplayable() ? "Active" : "Disposed"; //TO GET CURRENT STATUS OF FRAME DELETE
            delStatus = delete.getdelStatus(); //IF A PRODUCT IS DELETED, THEN THIS BOOLEAN VARIABLE WILL BE TRUE
            
            //USING IF STRUCTURE TO RESET VALUE OF TIMER EVERYTIME FRAME STATUS IS RESET
            if (dltfrmStatus.equals("Active") || dltfrmStatus.equals("Disposed")){
                i=0;
            }//END IF   
                
                /*USING IF ELSE STRUCTURE TO SHOW DEDUCTED VALUE OF
                  INVENTORY VALUE, QUANTITY VALUE AND PRODUCT NUMBER'
                  IF A PRODUCT HAS BEEN SUCCESSFULLY DELETED*/
                if (delStatus==true){
                    
                    /*VARIABLE DECLARATION TO GET VALUE OF METHOD THAT BEEN
                      INVOKED FROM DELETE OBJECT*/
                    
                    double invVal = delete.getcurrentinvValue();
                    int invQty = delete.getQuantity();
                    
                    //SET JLABEL WITH THE VALUE THAT WE INVOKED BEFORE
                    lblminusinvVal.setText("- " + String.format("RM %,.2f", invVal));
                    lblminusProd.setText("- 1 Product");
                    lblminusQty.setText("- " + invQty + " Quantity");

                        /*THIS IS TO SHOW AND HIDE THE VALUE HAVE BEEN DEDUCTED
                          AUTOMATICALLY AFTER A FEW SECONDS*/
                        timer = new Timer(700, new ActionListener() {
                        @Override
                        public void actionPerformed(ActionEvent e) {

                            i++;
                            if(i==1){

                            }//END IF

                            if(i==25){
                                delete.delStatus = false;
                                delStatus = delete.getdelStatus();
                                lblminusinvVal.setText(" ");
                                lblminusProd.setText(" ");
                                lblminusQty.setText(" ");
                            }//END IF

                            if(i==26){
                                timer.stop();
                                i=0;
                            }//END IF

                        }//END PUBLIC VOID
                        });
                        timer.start();


                }else if (delStatus==false) {
                           lblminusinvVal.setText(" ");
                           lblminusProd.setText(" ");
                           lblminusQty.setText(" ");

                }//END If

        } catch (NullPointerException e) {
            System.out.println(" :D ");
        }//END TRY CATCH

    }//END METHOD
    
    //METHOD TO EXPORT JTABLE VALUE TO TEXT FILE
    private void exporttoFile(){
            //USING TRY CATCH
           try{
                String strPath = "C:/Export.txt"; //EXPORT TO THIS PATH
                //FILE PATH
               File file = new File(strPath);
               
                //CREATE FILE IF NOT EXISTS
               if(!file.exists()){
                   file.createNewFile();
               }//END IF
               
               //CREATE OBJECT FILEWRITER AND BUFFEREDWRITER
               FileWriter fw = new FileWriter(file.getAbsoluteFile());
               BufferedWriter bw = new BufferedWriter(fw);
               
               //loop for jtable rows
               for(int i = 0; i < jTable1.getRowCount(); i++){
                   //loop for jtable column
                   for(int j = 0; j < jTable1.getColumnCount(); j++){
                       bw.write(jTable1.getModel().getValueAt(i, j)+" ");
                   }//END INNER LOOP
               bw.write("\n");
               }//END OUTER LOOP
               bw.write("_____________________________________________\n"
                       + "Generated by Inventory Management System");
               //close BufferedWriter
               bw.close();
               //close FileWriter 
               fw.close();
               playExclamation();
               new msgBox("Table has been exported to " + strPath,"Data Exported").showinfoMsg();
               
               }catch(Exception ex){
                   ex.printStackTrace();
               }//END TRY CATCH
           } //END METHOD
    

    private void eachinventoryValue(){
        
    //USING TRY CATCH
        try {
        int selectedRowIndex = jTable1.getSelectedRow();
        int getselectedId = Integer.parseInt(jTable1.getModel().getValueAt(selectedRowIndex, 0).toString());
        int selectedRow = jTable1.getSelectedRow();    
        int prodQty = Integer.parseInt(jTable1.getValueAt(selectedRow, 3).toString());
        double prodPrice = Double.parseDouble(jTable1.getValueAt(selectedRow, 4).toString());
        double totPrice = prodPrice*prodQty;
        lblindInvVal.setText("Product ID " + getselectedId +" has inventory value of " + String.format("RM %,.2f", totPrice)); 
        lblindInvVal.setForeground(new Color(0,153,153));
        } catch (ArrayIndexOutOfBoundsException e) {
            lblindInvVal.setText("No item selected.");
            lblindInvVal.setForeground(new Color(149, 149, 149));
        }//END TRY CATCH
        
    }//END METHOD
    
    //METHOD TO SEARCH FOR PRODUCT
    private void enterSearch(){
       
        
        //USING IF STRUCTURE
        if (!txtsearchBox.getText().equals("Search here...") && !txtsearchBox.getText().equals("")){
                frmSearch search = new frmSearch();

            //USING FOR SEARCH ANIMATION    
            timer = new Timer(50, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                  i++;
                    if(i==1){
                        loading.setVisible(true);
                        loading.lblLoad.setText("Searching . . .");
                    }//END IF
                    
                    if(i==25){
                        loading.dispose();
                        
                        //CREATE AND SHOW FRAME SEARCH
                         //INVOKE WITH PARAMETER OF SEARCH STRING VALUE
                        search.searchTable(txtsearchBox.getText());
                        search.setVisible(true);
                        
                    }//END IF
                    
                    if(i>=26){
                        txtsearchBox.setText("");
                        timer.stop();
                        i=0;
                    }//END IF
            }//END PUBLIC VOID
        });
        timer.start();
                
        }else{
            playExclamation();
            new msgBox("Please input search value !","ERROR").showerrorMsg();
        }//END IF
        
    }//END METHOD
    
    //METHOD TO RELOAD TABLE
     /*THIS METHOD IS USED WITH EVENT OF FORMWINDOWACTIVATED
       TO GET REALTIME VALUE OF PRODUCTS FROM TEXTFILE TO JTABLE*/
    public void reloadTable(){
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        loadData();
        eachinventoryValue();
    }//END METHOD
    
    //METHOD TO LOAD DATA OF PRODUCTS FROM TEXT FILE TO JTABLE
    public void loadData(){
        String filePath = "C:/Products.txt";
        File file = new File(filePath);
        //USING TRY CATCH
        try{
             BufferedReader br = new BufferedReader(new FileReader(file));
            // get the first line
            // get the columns name from the first line
            // set columns name to the jtable model
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();

            // get lines from txt file
            Object[] tableLines = br.lines().toArray();
            
            // extratct data from lines
            // set data to jtable model
            for(int i = 0; i < tableLines.length; i++)
            {
                String line = tableLines[i].toString().trim();
                String[] dataRow = line.split(",");
                model.addRow(dataRow);
            }
            
            //TO REMOVE NULL PRODUCTS FROM JTABLE
            int i = 0;
            while(i < model.getRowCount()) {
                if (((String)model.getValueAt(i, 1)).equals("null")) {
                model.removeRow(i);
                }else {
                ++i;
                }//END IF
            }//END DO
            
            //SHOW TOTAL PRODUCTS
            lblitemNo.setText(String.valueOf(model.getRowCount())); 
            
            //SHOW TOTAL QUANTITY
             int totalQty = 0;
                for(int j = 0; j < jTable1.getRowCount(); j++){
                    totalQty = totalQty + Integer.parseInt(jTable1.getValueAt(j, 3).toString());
                }//END DO
            lbltotQty.setText(Integer.toString(totalQty));
            
            //SHOW INVENTORY VALUE
            double totalInv = 0;
            for(int k = 0; k < jTable1.getRowCount(); k++){
                    int prodQty = Integer.parseInt(jTable1.getValueAt(k, 3).toString());
                    double prodPrice = Double.parseDouble(jTable1.getValueAt(k, 4).toString());
                    double totalPrice = prodQty * prodPrice;
                    totalInv = totalInv + totalPrice;
                }//END DO
            lblinventoryVal.setText(String.format("  RM %,.2f  ", totalInv));
        
        }catch (FileNotFoundException e) {
            new msgBox("Unable to load data to table. File "+ filePath + " not found !" ,"ERROR").showerrorMsg();
        }catch(Exception e){
            new msgBox("Unknown error occured !","ERROR").showerrorMsg();

       }//END TRY CATCH
        
    }//END METHOD
   
   //METHOD TO PLAY EXCLAMATION SOUND FOR MSGBOX
    private void playExclamation(){
        final Runnable runnable =
        (Runnable) Toolkit.getDefaultToolkit().getDesktopProperty("win.sound.asterisk");
        if (runnable != null) runnable.run();
    }//END METHOD
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMainmenu().setVisible(true);
            }
        });
    }//END MAIN

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTree jTree1;
    private javax.swing.JMenuItem jmiAbout;
    private javax.swing.JMenuItem jmiAdd;
    private javax.swing.JMenuItem jmiDelete;
    private javax.swing.JMenuItem jmiEdit;
    private javax.swing.JMenuItem jmiExport;
    private javax.swing.JMenuItem jmiLogout;
    private javax.swing.JMenuItem jmiMngAcc;
    private javax.swing.JMenuItem jmiSearch;
    private javax.swing.JMenuItem jmiStaffAcc;
    private javax.swing.JMenuItem jmicrtAcc;
    private javax.swing.JMenuItem jmikbshrtct;
    private javax.swing.JCheckBoxMenuItem jmiprodinvVal;
    private javax.swing.JCheckBoxMenuItem jmitotinvVal;
    private javax.swing.JCheckBoxMenuItem jmitotprodCnt;
    private javax.swing.JCheckBoxMenuItem jmitotprodQty;
    private javax.swing.JPanel jpinvVal;
    private javax.swing.JPanel jptotProd;
    private javax.swing.JPanel jptotQty;
    private javax.swing.JRadioButtonMenuItem jrbCheerUp;
    private javax.swing.JRadioButtonMenuItem jrbDefault;
    private javax.swing.JRadioButtonMenuItem jrbOceanFive;
    private javax.swing.JLabel lblindInvVal;
    private javax.swing.JLabel lblinventoryVal;
    private javax.swing.JLabel lblitemNo;
    private javax.swing.JLabel lblminusProd;
    private javax.swing.JLabel lblminusQty;
    private javax.swing.JLabel lblminusinvVal;
    private javax.swing.JLabel lblsessionName;
    private javax.swing.JLabel lblsessionName1;
    private javax.swing.JLabel lbltotQty;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel subPanel;
    private javax.swing.JLabel txtlblinvval;
    private javax.swing.JLabel txtlbltotProd;
    private javax.swing.JLabel txtlbltotQty;
    private javax.swing.JTextField txtsearchBox;
    // End of variables declaration//GEN-END:variables
}
