package inventory.gui;

import java.awt.Component;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JTextField;

/**
 *
 * @author Muhamad Ashraff
 */
public class frmMngAcc extends javax.swing.JFrame {

    /**
     * Creates new form frmMngAcc
     */
    public frmMngAcc() {
        initComponents();
        
    }//DEFAULT CONSTRUCTOR
   
    public frmMngAcc(int staffId){
        initComponents();
        loadData(staffId);
        lblpassChecker.setText("");
        lblpostcodeChecker.setText("");
        jSavepass.setEnabled(false);
    }//CONSTRUCTOR WITH PARAMETER
    
    //METHOD LOADDATA() 
      //A METHOD USED TO LOAD DATA OF STAFF TO JTEXTFIELD
    public void loadData(int n){
        
      //VARIABLE DECLARATION AND ASSIGNMENT  
      String strPath = "C:/Staff.txt";
      n = n-1;
      String line;
      
      //USING TRY CATCH BLOCKS
      try (BufferedReader br = new BufferedReader(new FileReader(strPath))) {
          
           //USING FOR LOOP
          for (int i = 0; i < n; i++)
              br.readLine();
          line = br.readLine();
          String[] staffDetails = line.split(","); //SPLIT COMMA IN A LINE
          
          //LOAD DATA OF STAFF TO JTEXTFIELD
          txtStaffId.setText(staffDetails[0]);
          txtfirstName.setText(staffDetails[2]);
          txtmiddleName.setText(staffDetails[3]);
          txtlastName.setText(staffDetails[4]);
          
          txthouseNo.setText(staffDetails[5]);
          txtbuildingNo.setText(staffDetails[6]);
          txtStreet.setText(staffDetails[7]);
          txtPostcode.setText(staffDetails[8]);
          txtCity.setText(staffDetails[9]);
          txtState.setText(staffDetails[10]);

          System.out.println(line);
      }
      catch(IOException e){
        System.out.println(e);
      }catch (IndexOutOfBoundsException e){
        new msgBox("Data Not Found !","ERROR").showinfoMsg();
      }//END TRY CATCH
        
    }//END METHOD

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelAccountdetails = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtStaffId = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        txtfirstName = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtmiddleName = new javax.swing.JTextField();
        txtlastName = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txthouseNo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtbuildingNo = new javax.swing.JTextField();
        txtStreet = new javax.swing.JTextField();
        txtPostcode = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        txtState = new javax.swing.JTextField();
        jbSavenameaddress = new javax.swing.JButton();
        lblpostcodeChecker = new javax.swing.JLabel();
        panelAccountdetails1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jpNewpass = new javax.swing.JPasswordField();
        jpConfPass = new javax.swing.JPasswordField();
        jSavepass = new javax.swing.JButton();
        lblpassChecker = new javax.swing.JLabel();
        jbClose = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Manage My Account");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(181, 79, 119));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("My Account");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(37, 37, 37))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(323, 323, 323)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelAccountdetails.setBackground(new java.awt.Color(255, 255, 255));
        panelAccountdetails.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel4.setBackground(new java.awt.Color(48, 213, 200));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Account Details");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        jLabel4.setText("Staff ID : ");

        jLabel5.setText("First Name :");

        txtStaffId.setEditable(false);
        txtStaffId.setBackground(new java.awt.Color(255, 255, 255));
        txtStaffId.setForeground(new java.awt.Color(0, 204, 204));
        txtStaffId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtStaffIdMousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("STAFF NAME");

        jLabel12.setText("Middle Name :");

        jLabel13.setText("Last Name :");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("STAFF ADDRESSES");

        jLabel11.setText("House No :");

        jLabel14.setText("Building :");

        jLabel15.setText("Street :");

        jLabel16.setText("Postcode :");

        jLabel17.setText("City :");

        jLabel18.setText("State :");

        txtPostcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPostcodeKeyReleased(evt);
            }
        });

        jbSavenameaddress.setText("Save");
        jbSavenameaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSavenameaddressActionPerformed(evt);
            }
        });

        lblpostcodeChecker.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblpostcodeChecker.setForeground(new java.awt.Color(255, 0, 102));
        lblpostcodeChecker.setText("notifypostcodenotint");

        javax.swing.GroupLayout panelAccountdetailsLayout = new javax.swing.GroupLayout(panelAccountdetails);
        panelAccountdetails.setLayout(panelAccountdetailsLayout);
        panelAccountdetailsLayout.setHorizontalGroup(
            panelAccountdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelAccountdetailsLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panelAccountdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelAccountdetailsLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txthouseNo, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAccountdetailsLayout.createSequentialGroup()
                        .addGroup(panelAccountdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelAccountdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtbuildingNo)
                            .addComponent(txtStreet)
                            .addComponent(txtPostcode)
                            .addComponent(txtCity)
                            .addComponent(txtState, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)))
                    .addGroup(panelAccountdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(panelAccountdetailsLayout.createSequentialGroup()
                            .addComponent(lblpostcodeChecker)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbSavenameaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator1)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAccountdetailsLayout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(txtStaffId, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelAccountdetailsLayout.createSequentialGroup()
                            .addGroup(panelAccountdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel12)
                                .addComponent(jLabel5)
                                .addComponent(jLabel13))
                            .addGap(18, 18, 18)
                            .addGroup(panelAccountdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtfirstName)
                                .addComponent(txtmiddleName)
                                .addComponent(txtlastName, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)))
                        .addComponent(jSeparator2)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        panelAccountdetailsLayout.setVerticalGroup(
            panelAccountdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAccountdetailsLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelAccountdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtStaffId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(panelAccountdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtfirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAccountdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtmiddleName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAccountdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(txtlastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(panelAccountdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txthouseNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAccountdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtbuildingNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAccountdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAccountdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtPostcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAccountdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAccountdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(panelAccountdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSavenameaddress)
                    .addComponent(lblpostcodeChecker))
                .addContainerGap())
        );

        panelAccountdetails1.setBackground(new java.awt.Color(255, 255, 255));
        panelAccountdetails1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel5.setBackground(new java.awt.Color(48, 213, 200));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 255, 204));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Change Password");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        jLabel8.setText("New Password :");

        jLabel9.setText("Confirm Password :");

        jpConfPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jpConfPassKeyReleased(evt);
            }
        });

        jSavepass.setText("Save");
        jSavepass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSavepassActionPerformed(evt);
            }
        });

        lblpassChecker.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblpassChecker.setForeground(new java.awt.Color(255, 0, 102));
        lblpassChecker.setText("notifypassnotmatch");

        javax.swing.GroupLayout panelAccountdetails1Layout = new javax.swing.GroupLayout(panelAccountdetails1);
        panelAccountdetails1.setLayout(panelAccountdetails1Layout);
        panelAccountdetails1Layout.setHorizontalGroup(
            panelAccountdetails1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelAccountdetails1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panelAccountdetails1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblpassChecker)
                    .addGroup(panelAccountdetails1Layout.createSequentialGroup()
                        .addGroup(panelAccountdetails1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelAccountdetails1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSavepass, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelAccountdetails1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jpNewpass)
                                .addComponent(jpConfPass, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAccountdetails1Layout.setVerticalGroup(
            panelAccountdetails1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAccountdetails1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(panelAccountdetails1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jpNewpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAccountdetails1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jpConfPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAccountdetails1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSavepass)
                    .addComponent(lblpassChecker))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbClose.setBackground(new java.awt.Color(255, 153, 153));
        jbClose.setText("Close");
        jbClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(panelAccountdetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelAccountdetails1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jbClose, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelAccountdetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelAccountdetails1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbClose)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //TO SAVE NAME AND ADDRESS ONLY
    private void jbSavenameaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSavenameaddressActionPerformed
      
        //VARIABLE DECLARATION AND ASSIGNMENT 
       String strPath = "C:/Staff.txt";
      int n = Integer.parseInt(txtStaffId.getText());
      n = n-1;
      String line;
      
      //USING TRY CATCH BLOCKS
      try (BufferedReader br = new BufferedReader(new FileReader(strPath))) {
          for (int i = 0; i < n; i++)
          br.readLine();
          line = br.readLine();
          String[] staffPass= line.split(","); //SPLIT COMMA IN A LINE
          
          //USING IF STRUCTURE TO DETERMINE IF TEXTFIELD IS EMPTY OR NULLED
            //THROWS EXCEPTION IF ANY OF THE TEXTFIELD IS EMPTY OR NULLED
          
          //VARIABLE DECLARATION
           //ASSIGNED VALUE OF JTEXTFIELD TO VARIABLE DECLARED
          int staffId = Integer.parseInt(txtStaffId.getText());
          String pass = staffPass[1];
          String role = staffPass[11];
          String fName = txtfirstName.getText();
          String mName = txtmiddleName.getText();
          String lName = txtlastName.getText();
          String house = txthouseNo.getText();
          String building = txtbuildingNo.getText();
          String street = txtStreet.getText();
          int postcode = Integer.parseInt(txtPostcode.getText());
          String city = txtCity.getText();
          String state = txtState.getText();
          
          //COLLECTING DATA STRING TO UPDATE NEW DATA
          String oldStrdata = line;
          String newStrdata = staffId+","+pass+","+fName+","+mName+","+lName+","
                              +house+","+building+","+street+","+postcode+","+city+","+state+","+role;
          
          //CALL METHOD SAVEMODIFIEDDATA() WITH PARAMETER OF NEW AND OLD DATA
          savemodifiedData(oldStrdata, newStrdata);
          playExclamation();
          String message = "Details of staff with ID : "+ staffId + "\n" +
                             "has been successfully updated !" ;
          new msgBox(message,"Details updated !").showinfoMsg();
          
          //RELOAD DATA
          loadData(staffId);
      }catch (Exception e){
          playExclamation();
          new msgBox("Staff details cannot be nulled !","Error").showerrorMsg();
      }//END TRY CATCH
    }//GEN-LAST:event_jbSavenameaddressActionPerformed

    private void jSavepassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSavepassActionPerformed
      
      //VARIABLE DECLARATION AND ASSIGNMENT 
      String strPath = "C:/Staff.txt";
      int n = Integer.parseInt(txtStaffId.getText());
      n = n-1;
      String line;
      
      //USING TRY CATCH BLOCKS
      try (BufferedReader br = new BufferedReader(new FileReader(strPath))) {
          for (int i = 0; i < n; i++)
          br.readLine();
          line = br.readLine();
          String[] staffDetails = line.split(","); //SPLIT COMMA IN A LINE
          
          //VARIABLE DECLARATION
           //ASSIGNED VALUE OF JTEXTFIELD TO VARIABLE DECLARED          
          int staffId = Integer.parseInt(staffDetails[0]);
          String pass = String.valueOf(jpConfPass.getPassword());
          String fName = staffDetails[2];
          String mName = staffDetails[3];
          String lName = staffDetails[4];
          String house = staffDetails[5];
          String building = staffDetails[6];
          String street = staffDetails[7];
          int postcode = Integer.parseInt(staffDetails[8]);
          String city = staffDetails[9];
          String state = staffDetails[10];
          String role = staffDetails[11];
          
          //COLLECTING DATA STRING TO UPDATE NEW DATA
          String oldStrdata = line;
          String newStrdata = staffId+","+pass+","+fName+","+mName+","+lName+","
                              +house+","+building+","+street+","+postcode+","+city+","+state+","+role;
          
          //CALL METHOD SAVEMODIFIEDDATA() WITH PARAMETER OF NEW AND OLD DATA
          savemodifiedData(oldStrdata, newStrdata);
          playExclamation();
          String message = "Password of staff with ID : "+ staffId + "\n" +
                             "has been successfully updated !" ;
          new msgBox(message,"Password updated !").showinfoMsg();
          
          //RELOAD DATA
          loadData(staffId);
          
          //CLEAR JPASSWORD BOX
          jpNewpass.setText("");
          jpConfPass.setText("");
          jSavepass.setEnabled(false);
      }catch (Exception e){   
          new msgBox("Unable to save new password details.","Error").showerrorMsg();
      }//END TRY CATCH
    }//GEN-LAST:event_jSavepassActionPerformed

    private void jbCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCloseActionPerformed
        dispose();
    }//GEN-LAST:event_jbCloseActionPerformed

    private void jpConfPassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpConfPassKeyReleased
        //EVENT KEY RELEASE FOR JPASSWORD
        
        //DECLARING VARIABLE AND ASSIGNED VALUE TO VARIABLE DECLARED
        String passTxt = String.valueOf(jpNewpass.getPassword());
        String confpassTxt = String.valueOf(jpConfPass.getPassword());
        
        //USING IF STRUCTURE
          //IF BOTH JPASSWORD FIELD ARE MATCHED
          //THEN BUTTON SAVE WILL BE ENABLED ELSE WILL BE DISABLED
        if (passTxt.equals(confpassTxt)){
            lblpassChecker.setText("");
            jSavepass.setEnabled(true);
        }else{
            lblpassChecker.setText("Password does not match.");
            jSavepass.setEnabled(false);
        }//END IF
    }//GEN-LAST:event_jpConfPassKeyReleased

    private void txtPostcodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPostcodeKeyReleased
        //USING TRY CATCH TO DETERMINE IF USER INPUT OF POSTCODE IS AN INTEGER FORMAT
        try {
        Integer.parseInt(txtPostcode.getText());
        lblpostcodeChecker.setText("");
        jbSavenameaddress.setEnabled(true);
        }
        catch (NumberFormatException e) {
            //IF USER INPUT OTHER THAN INTEGER VALUE ON POSTCODE THEN SHOW THIS ERROR LABEL
            lblpostcodeChecker.setText("Warning : Postcode must be numberic value only");
            jbSavenameaddress.setEnabled(false);
        }//END TRY CATCH
    }//GEN-LAST:event_txtPostcodeKeyReleased

    private void txtStaffIdMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtStaffIdMousePressed
        //ERROR MSGBOX WILL BE SHOWN IF USER WANT TO EDIT STAFF ID
        playExclamation();
        new msgBox("Product ID cannot be modified.\nIt is an auto generated by the program !","WARNING").showwarningMsg();
    }//GEN-LAST:event_txtStaffIdMousePressed

    //METHOD TO SAVE NEW DATA
    private void savemodifiedData(String oldStr, String newStr){
    String strPath = "C:/Staff.txt";
        File fileToBeModified = new File(strPath);
         
        String oldContent = "";
        BufferedReader reader = null;
        FileWriter writer = null;
         
        //USING TRY CATCH
        try
        {   
            //READ LINES OF TXT FILE
            reader = new BufferedReader(new FileReader(fileToBeModified));
            String line = reader.readLine();
             
            while (line != null) 
            {
                oldContent = oldContent + line + System.lineSeparator();
                 
                line = reader.readLine();
            }//ENDDO
             
            //REPLACING WITH NEW DATA
            String newContent = oldContent.replaceAll(oldStr, newStr);

            //REWRITE THE NEW DATA 
            writer = new FileWriter(fileToBeModified);
            writer.write(newContent);
            System.out.println("DONE !");
        }
        catch (IOException e)
        {
            e.printStackTrace();
        }//END TRY CATCH
        finally{
            try
            {
                //CLOSE READER & WRITER
                reader.close();
                writer.close();
            } 
            catch (IOException e) 
            {
                e.printStackTrace();
            }//END NESTED TRY CATCH
        }//END FINALLY
    }//END METHOD SAVEMODIFIEDDATA
    
    //METHOD TO PLAY EXCLAMATION SOUND FOR MSGBOX
    private void playExclamation(){
        final Runnable runnable =
        (Runnable) Toolkit.getDefaultToolkit().getDesktopProperty("win.sound.asterisk");
        if (runnable != null) runnable.run();
    }//END METHOD
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMngAcc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMngAcc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMngAcc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMngAcc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMngAcc().setVisible(true);
            }
        });
    }//END MAIN

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton jSavepass;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton jbClose;
    private javax.swing.JButton jbSavenameaddress;
    private javax.swing.JPasswordField jpConfPass;
    private javax.swing.JPasswordField jpNewpass;
    private javax.swing.JLabel lblpassChecker;
    private javax.swing.JLabel lblpostcodeChecker;
    private javax.swing.JPanel panelAccountdetails;
    private javax.swing.JPanel panelAccountdetails1;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtPostcode;
    private javax.swing.JTextField txtStaffId;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtStreet;
    private javax.swing.JTextField txtbuildingNo;
    private javax.swing.JTextField txtfirstName;
    private javax.swing.JTextField txthouseNo;
    private javax.swing.JTextField txtlastName;
    private javax.swing.JTextField txtmiddleName;
    // End of variables declaration//GEN-END:variables
}
