/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventory.gui;

import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import javax.swing.Timer;

/**
 *
 * @author Muhamad Ashraff
 */
public class frmminiSearch extends javax.swing.JFrame {

    /**
     * Creates new form frmminiSearch
     */
    Timer timer;
    int i = 0;
    frmsrchLoad loading = new frmsrchLoad();
    
    
    public frmminiSearch() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtsrchBox = new javax.swing.JTextField();
        jbSearch = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Search");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(81, 210, 183));

        txtsrchBox.setBackground(new java.awt.Color(81, 210, 183));
        txtsrchBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtsrchBox.setForeground(new java.awt.Color(255, 255, 255));
        txtsrchBox.setText("Search for...");
        txtsrchBox.setBorder(null);
        txtsrchBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtsrchBoxFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtsrchBoxFocusLost(evt);
            }
        });
        txtsrchBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtsrchBoxKeyPressed(evt);
            }
        });

        jbSearch.setText("Search");
        jbSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSearchActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/searchIcon.png"))); // NOI18N

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtsrchBox)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtsrchBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jbSearch)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSearchActionPerformed
        search(); //CALL METHOD SEARCH()
    }//GEN-LAST:event_jbSearchActionPerformed

    private void txtsrchBoxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtsrchBoxFocusGained
        
        //USING IF STRUCTURE
           //IF JTEXTFIELD IS GAINED FOCUS. THEN REMOVE TEXT PLACEHOLDER
        if (txtsrchBox.getText().equals("Search for...")){
            txtsrchBox.setText("");
        }//END IF
        
    }//GEN-LAST:event_txtsrchBoxFocusGained

    private void txtsrchBoxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtsrchBoxFocusLost
        //WHEN JTEXTFIELD IS LOST FOCUS
        //USING IF STRUCTURE
          //IF JTEXTFIELD IS EMPTY OR NULL PUT BACK PLACEHOLDER TEXT
        if (txtsrchBox.getText().equals("")){
            txtsrchBox.setText("Search for...");
        }//END IF
        
    }//GEN-LAST:event_txtsrchBoxFocusLost

    private void txtsrchBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsrchBoxKeyPressed
        //USING IF STRUCTURE TO DETERMINE IF USING INPUT ENTER KEY
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            search(); //CALL METHOD SEARCH
        }//END IF
    }//GEN-LAST:event_txtsrchBoxKeyPressed
    
    //METHOD TO SEARCH
    private void search(){
        
        //USING IF ELSE STRUCTURE
          //TO DETERMINE IF BOTH JTEXTFIELD OF SEARCH BOX IS FILLED WITH
          //VALUE OF SEARCH STRING, THEN CREATE NEW SEARCH FRAME
        if (!txtsrchBox.getText().equals("Search for...") && !txtsrchBox.getText().equals("")){
            frmSearch search = new frmSearch();
            timer = new Timer(50, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                  i++;
                    if(i==1){
                        loading.setVisible(true);
                        loading.lblLoad.setText("Searching . . .");
                        dispose();
                    }//END IF
                    
                    if(i==25){
                        loading.dispose();
                        search.searchTable(txtsrchBox.getText());
                        search.setVisible(true);
                        
                    }
                    
                    if(i>26){
                        timer.stop();
                        i=0;
                    }
            }//END PUBLIC VOID
        });
        timer.start();
        }else{
            //IF NONE OF THE CONDITION IS MET, THEN AN ERROR MESSAGEBOX WILL BE SHOWN
            playExclamation();
            new msgBox("Please input search value !","ERROR").showerrorMsg();
        }//END IF
            
    }//END METHOD
    
      //METHOD TO PLAY EXCLAMATION SOUND FOR MSGBOX
    private void playExclamation(){
        final Runnable runnable =
        (Runnable) Toolkit.getDefaultToolkit().getDesktopProperty("win.sound.asterisk");
        if (runnable != null) runnable.run();
    }//END METHOD
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmminiSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmminiSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmminiSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmminiSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmminiSearch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbSearch;
    private javax.swing.JTextField txtsrchBox;
    // End of variables declaration//GEN-END:variables
}
